// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/network/standard"
	"github.com/linzijie1998/bytedance_camp_douyin/biz/middleware"
	"github.com/linzijie1998/bytedance_camp_douyin/global"
	"github.com/linzijie1998/bytedance_camp_douyin/initialize"
)

func main() {
	global.DOUYIN_VIPER = initialize.InitViper("config.yaml")
	global.DOUYIN_LOGGER = initialize.InitZapLogger()
	global.DOUYIN_DB = initialize.InitGormMySQL()
	global.DOUYIN_REDIS = initialize.InitRedis()
	initialize.AutoMigrateTables()

	h := server.Default(
		// https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/stream/
		server.WithStreamBody(true),
		server.WithAltTransport(standard.NewTransporter),
		server.WithHostPorts(global.DOUYIN_CONFIG.Hertz.WithHostPorts()),
	)

	// 静态资源注册，展示视频和头像
	initialize.MakeUploadRootDirs()
	h.Static("/videos", global.DOUYIN_CONFIG.Upload.UploadRoot)
	h.Static("/covers", global.DOUYIN_CONFIG.Upload.UploadRoot)

	// 日志中间件
	h.Use(middleware.AccessLog())

	register(h)
	h.Spin()
}
