// Code generated by hertz generator.

package base

import (
	"context"
	"fmt"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/linzijie1998/bytedance_camp_douyin/biz/cache"
	"github.com/linzijie1998/bytedance_camp_douyin/biz/dal"
	base "github.com/linzijie1998/bytedance_camp_douyin/biz/model/douyin/base"
	"github.com/linzijie1998/bytedance_camp_douyin/global"
	"github.com/linzijie1998/bytedance_camp_douyin/model"
	"github.com/linzijie1998/bytedance_camp_douyin/util"
	"path"
	"path/filepath"
)

// PublishAction 需要JWT鉴权, 验证通过会在请求上下文中添加"token_user_id"信息.
// @router /douyin/publish/action/ [POST]
func PublishAction(ctx context.Context, c *app.RequestContext) {
	resp := new(base.PublishActionResp)
	// 从请求上下文中提取"token_user_id"
	title := c.PostForm("title")
	rawID, exists := c.Get("token_user_id")
	if !exists {
		global.DOUYIN_LOGGER.Debug("未从请求上下文中解析到userID")
		resp.StatusCode = 1
		c.JSON(consts.StatusBadRequest, resp)
		return
	}
	userID := int64(rawID.(uint))

	file, err := c.FormFile("data")
	if err != nil {
		global.DOUYIN_LOGGER.Debug(fmt.Sprintf("未接收到视频数据 err: %v", err))
		resp.StatusCode = 1
		c.JSON(consts.StatusBadRequest, resp)
		return
	}

	filename, err := util.GenerateFilenameByUploadDatetime(file.Filename)
	if err != nil {
		global.DOUYIN_LOGGER.Debug(fmt.Sprintf("文件名生成错误 err: %v", err))
		resp.StatusCode = 1
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	video := model.Video{
		UserInfoID: userID,
		Title:      title,
		VideoPath:  filename,
		CoverPath:  fmt.Sprintf("%s.jpg", filename),
	}

	videoPath := filepath.Join(global.DOUYIN_CONFIG.Video.VideoUploadPath, video.VideoPath)
	coverPath := filepath.Join(global.DOUYIN_CONFIG.Video.CoverUploadPath, video.CoverPath)

	if err := c.SaveUploadedFile(file, videoPath); err != nil {
		global.DOUYIN_LOGGER.Debug(fmt.Sprintf("视频保存失败 err: %v", err))
		resp.StatusCode = 1
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	if err := util.GetCover(videoPath, coverPath, "00:00:02"); err != nil {
		global.DOUYIN_LOGGER.Debug(fmt.Sprintf("视频封面截取失败 err: %v", err))
		video.CoverPath = ""
	}

	if err := dal.CreateVideoInfo(&video); err != nil {
		global.DOUYIN_LOGGER.Debug(fmt.Sprintf("视频信息存储失败 err: %v", err))
		resp.StatusCode = 1
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	c.JSON(consts.StatusOK, resp)
	global.DOUYIN_LOGGER.Info(fmt.Sprintf("ID为%d的用户上传了视频%s", userID, videoPath))
}

// PublishList .
// @router /douyin/publish/list/ [GET]
func PublishList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req base.PublishListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp := new(base.PublishListResp)

	if req.Token == "" {
		global.DOUYIN_LOGGER.Info("未携带Token, 无法解析上传视频信息")
		resp.StatusCode = 1
		c.JSON(consts.StatusOK, resp)
		return
	}
	j := util.NewJWT()
	claim, err := j.ParseToken(req.Token)
	if err != nil {
		global.DOUYIN_LOGGER.Info(fmt.Sprintf("Token解析失败 err: %v", err))
		resp.StatusCode = 1
		c.JSON(consts.StatusBadRequest, resp)
		return
	}

	userID := int64(claim.UserInfo.ID)

	videoInfos, err := dal.QueryVideoInfoByUserInfoID(userID)
	if err != nil {
		global.DOUYIN_LOGGER.Debug(fmt.Sprintf("视频信息查询失败 err: %v", err))
		resp.StatusCode = 1
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	userInfos, err := dal.QueryUserInfoByUserID(userID)
	if err != nil {
		global.DOUYIN_LOGGER.Debug(fmt.Sprintf("用户信息查询失败 err: %v", err))
		resp.StatusCode = 1
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}
	if len(userInfos) != 1 {
		global.DOUYIN_LOGGER.Warn(fmt.Sprintf("查询到超过一条的ID为%d的用户信息", userID))
		resp.StatusCode = 1
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	followCnt, _ := cache.GetFollowCount(int64(userInfos[0].ID))
	followerCnt, _ := cache.GetFollowerCount(int64(userInfos[0].ID))

	var user = new(base.User)
	user.ID = int64(userInfos[0].ID)
	user.Name = userInfos[0].Name
	user.FollowCount = &followCnt
	user.FollowerCount = &followerCnt
	user.IsFollow = false // 自己不能关注自己

	videoList := make([]*base.Video, len(videoInfos))
	for i, info := range videoInfos {
		// 查询点赞信息
		isFavorite, err := cache.GetFavoriteState(userID, int64(info.ID))
		if err != nil {
			global.DOUYIN_LOGGER.Debug(fmt.Sprintf("查询点赞信息失败 err: %v", err))
			resp.StatusCode = 1
			c.JSON(consts.StatusInternalServerError, resp)
			return
		}

		followCnt, _ := cache.GetFollowCount(int64(info.ID))
		followerCnt, _ := cache.GetFollowerCount(int64(info.ID))

		var video = new(base.Video)
		video.ID = int64(info.ID)
		video.PlayURL = util.GetPlayURLByFilename(path.Base(info.VideoPath))
		video.CoverURL = util.GetCoverURLByFilename(path.Base(info.CoverPath))
		video.FavoriteCount = followCnt
		video.CommentCount = followerCnt
		video.IsFavorite = isFavorite
		video.Author = user
		videoList[i] = video
	}
	resp.VideoList = videoList
	c.JSON(consts.StatusOK, resp)
}
